### ISSUE TITLE
Occasional code tags

### ISSUE THREAD

**Issue by enver** [saltstack-formulas/sysctl-formula#11]
Hi, it would be great if you could create tags on all formulas (quarterly, monthly,...) so they could be easily used without risking future updates breaking something. This way users could easily use formulas as:

```
gitfs_remotes:
  - https://github.com/saltstack-formulas/sysctl-formula:
    - base: <Some tag>
```

without creating fork for each formula they use. Then as formulas are updated users could test new versions and pull them in their system in a more controlled way.

**Comment by aboe76** [comment]
@enver I think this needs to be addressed at a higher level,
@basepi could you take a look at the question?

**Comment by basepi** [comment]
Hmm, this might be a good one to file on the salt proper repository, it's not specific to this formula. Mind re-opening this issue on saltstack/salt and closing it here?

**Comment by enver** [comment]
Created new [ticket](https://github.com/saltstack/salt/issues/31211) on saltstack/salt
