### ISSUE TITLE
Fixed/Tested with Centos 6/7

### ISSUE THREAD

**Issue by solomongifford** [saltstack-formulas/sysctl-formula#21]
Appears this wasn't working with RedHat family 6/7.  /etc/sysctl.conf is a file, but was being used as a directory.  Also, /etc/sysctl.d exists on both.  Finally, the package names are different for 6 & 7.  I've created https://github.com/saltstack-formulas/sysctl-formula/pull/20 to resolve.

**Comment by javierbertoli** [comment]
PR was merged long ago, closing.
