### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by n-rodriguez** [saltstack-formulas/sysctl-formula#24]
The goal of the previous PR is to update https://github.com/saltstack-formulas/sysctl-formula/blob/master/sysctl/map.jinja and remove the ugly backward compatiblility patch.

@myii  how do you want to do?

**Comment by myii** [comment]
@n-rodriguez For these non-ng breaking changes, let's have two stages:

1. PR to add deprecation warning -- gives a little time for users to get prepared.
2. PR to merge `v1.0.0`.
